# agent/nodes/cold_start/hardware_research.py
"""
Autonomous hardware research.

Given a free-text device/chip description from the user, resolves it into a
HardwareConstraints object via a three-stage pipeline:

  1. LOCAL DB — fuzzy-match against data/devices.csv (Kaggle phone specs DB,
     generated by scripts/refresh_device_db.py). No API calls. Fast and free.
  2. EXA FALLBACK — if the device isn't in the local DB, use Exa web search
     to find spec snippets.
  3. LLM RESOLVE — the orchestrator model interprets either local DB results or web
     snippets and emits DEVICE-SPECIFIC values only: usable RAM, storage budget, and
     the reference chip. The remaining gates (latency, power, throughput floor) are
     fixed system constants from config.config (HW_*), not device-derived. The deployed
     model may be BF16, Q8_0, or Q4_K_M — nothing here assumes quantization.

Returns (HardwareConstraints, info_dict). info_dict is saved as device_research.json.
"""
import json
import os
import re

from agent.cost import tracked_anthropic_messages_create, tracked_exa_call
from config.android_pool import KNOWN_CHIPS, HardwareConstraints

# Valid chipset vocabulary. Previously derived from CHIP_SCALE_FACTORS, a table of
# invented per-chip decode multipliers; KNOWN_CHIPS is just the names, no performance
# claims attached.
REFERENCE_CHIPS = list(KNOWN_CHIPS)

_DEVICES_CSV = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "devices.csv")

_PROMPT = """You are the hardware-analysis stage of an autonomous on-device fine-tuning agent. \
A user wants to run a small language model on their phone. The deployed model MAY be full-precision \
(BF16) or quantized (Q8_0 / Q4_K_M) — do NOT assume it is quantized. Your ONLY job is to resolve \
how much RAM and storage the model may use on this device, from the device description and specs below.

YOU RESOLVE ONLY TWO VALUES — both are HARD gates on model selection:
- "usable_ram_mb": RAM available to the model at inference after the OS and foreground app. \
Any candidate variant whose PEAK RAM exceeds this is eliminated. Set it TOO LOW and every candidate \
is rejected (run fails); TOO HIGH and the chosen model out-of-memories on device. Typical Android \
OS + app footprint is ~1.5-2.0 GB, so usable ≈ total_RAM − 1500..2000 MB (e.g. 8 GB device → ~6000-6500 MB, \
6 GB → ~4000-4500 MB). Report the phone's TRUE usable RAM — a bigger budget is good, it lets the agent \
consider higher-quality (less-quantized) variants; the agent picks the smallest-RAM variant that still \
hits the accuracy goal on its own.
- "storage_budget_mb": on-disk weight-file budget. Full-precision (BF16) variants of ~3B models can \
exceed 6 GB on disk, so report the device's realistic free-storage allowance for a model file rather \
than an artificially small cap — under-reporting silently excludes the most capable variants.

You ALSO resolve "reference_chip" — the SoC governs decode speed, so it IS device-specific: \
map the device's chipset to the closest of {chips} by performance tier.

Everything else (latency target, power budget, decode-throughput floor) is a FIXED system constant \
configured elsewhere — do NOT output those; they are not device-specific.

Reply with ONLY a JSON object (no prose, no code fences) with keys:
- "device": resolved device name
- "chipset": the SoC (e.g. "Qualcomm Snapdragon 6 Gen 1"), or null if unknown
- "ram_gb": integer total RAM
- "storage_gb": integer total storage
- "usable_ram_mb": integer — RAM available to the model after OS/other apps (see guidance above)
- "storage_budget_mb": integer — on-disk model-file budget (see guidance above)
- "reference_chip": the closest of {chips} to this device's SoC by performance tier
- "rationale": one sentence covering how usable_ram_mb and storage_budget_mb were derived

User device description:
\"\"\"{description}\"\"\"

Device specs:
{snippets}
"""


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\n?", "", text)
        text = re.sub(r"\n?```$", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            raise ValueError(f"Hardware research did not return JSON: {text[:200]!r}")
        return json.loads(m.group())


def _lookup_local_db(description: str, log) -> str | None:
    """Fuzzy-match device name against the local Kaggle phone specs CSV.

    Returns a formatted string of matching rows, or None if no match or DB not found.
    """
    csv_path = os.path.abspath(_DEVICES_CSV)
    if not os.path.exists(csv_path):
        log("      [hw] Local device DB not found (run scripts/refresh_device_db.py to populate)")
        return None

    try:
        import csv
        # Extract search keywords from the description (device name words)
        desc_lower = description.lower()
        _STOP = {
            "the", "for", "and", "with", "that", "this", "run", "fine",
            "tune", "small", "model", "ram", "rom", "storage", "deploy",
            "deployment", "targeting", "efficiently", "should", "phone",
            "smartphone", "device", "mobile", "gb", "mb", "my", "using",
        }

        def _clean(tok: str) -> str:
            # strip surrounding punctuation ("9a," → "9a", "(2023)" → "2023")
            return tok.strip(".,;:()[]{}\"'").strip()

        keywords = []
        for w in (_clean(t) for t in desc_lower.split()):
            if not w or w in _STOP:
                continue
            has_digit = any(c.isdigit() for c in w)
            # Keep normal name words (len>2) AND short alphanumeric MODEL CODES that
            # contain a digit (e.g. "9a", "6a", "5g", "a14", "s24", "2023") — these are
            # the most discriminative tokens for a phone and were previously dropped by
            # the blanket len>2 rule, so single-distinctive-token phones (Pixel 6a,
            # Redmi 9A) never reached the >=2 match threshold. Drop pure memory sizes
            # like "2gb"/"128gb" (they don't appear in device names) and bare digits.
            if w.isdigit():
                # Keep short bare numbers — they are phone MODEL numbers ("12" in
                # "OnePlus 12", "8" in "Pixel 8") or years ("2023"). Only very long
                # digit runs (RAM/storage sizes already stripped of GB/MB) are dropped.
                if len(w) <= 4:
                    keywords.append(w)
                continue
            if w.endswith("gb") or w.endswith("mb"):
                continue
            if len(w) > 2 or has_digit:
                keywords.append(w)

        matches = []
        with open(csv_path, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                device_name = (row.get("device") or "").lower()
                # Score: how many keywords appear in the device name
                score = sum(1 for kw in keywords if kw in device_name)
                if score >= 2:  # need at least 2 keyword matches
                    matches.append((score, row))

        if not matches:
            log(f"      [hw] No match in local DB for keywords: {keywords[:6]}")
            return None

        # Sort by score (descending), take top 3
        matches.sort(key=lambda x: -x[0])
        top = matches[:3]

        snippets = []
        for score, row in top:
            ram = row.get("ram_mb", "?")
            storage = row.get("storage_mb", "?")
            chipset = row.get("chipset", "?")
            snippets.append(
                f"- {row['device']}: RAM={ram}MB, Storage={storage}MB, Chipset={chipset}"
            )

        log(f"      [hw] Local DB matched {len(matches)} device(s), using top {len(top)}")
        return "\n".join(snippets)

    except Exception as e:
        log(f"      [hw] Local DB lookup failed ({e})")
        return None


def _exa_snippets(description: str, log) -> str:
    """Web search fallback via Exa API."""
    try:
        from config.config import EXA_API_KEY
        from exa_py import Exa
        exa = Exa(api_key=EXA_API_KEY)
        r = tracked_exa_call(
            exa.search_and_contents,
            f"{description} smartphone chipset SoC RAM storage NPU full specifications",
            stage="hardware_research",
            model="search-and-contents",
            num_results=3, type="auto", text={"max_characters": 600},
        )
        return "\n".join(f"- {x.title[:80]}: {(x.text or '')[:300]}" for x in r.results)
    except Exception as e:
        log(f"      [hw] Exa lookup failed ({e}); proceeding from the description alone.")
        return "(no device specs available — resolve from the description text)"


def research_device(description: str, anthropic_client=None, log=print):
    """Resolve a device description into HardwareConstraints.

    Pipeline: local DB → Exa fallback → Claude LLM resolve.
    """
    if anthropic_client is None:
        import anthropic
        from config.config import ANTHROPIC_API_KEY, orchestrator_client_kwargs
        anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY, **orchestrator_client_kwargs())

    from config.config import ORCHESTRATOR_MODEL

    # Stage 1: try local device DB first (no API cost)
    snippets = _lookup_local_db(description, log)
    source = "local_db"

    # Stage 2: Exa web search fallback
    if snippets is None:
        log("      [hw] Falling back to Exa web search...")
        snippets = _exa_snippets(description, log)
        source = "exa"

    from config.config import (
        HW_LATENCY_TTFT_MS, HW_POWER_WATTS, HW_MIN_TOK_S, HW_FALLBACK_CHIP,
    )

    # Stage 3: LLM resolve — device-specific values only (RAM, storage, chip).
    try:
        resp = tracked_anthropic_messages_create(
            anthropic_client.messages,
            stage="hardware_research",
            model=ORCHESTRATOR_MODEL, max_tokens=700,
            messages=[{"role": "user", "content": _PROMPT.format(
                chips=REFERENCE_CHIPS, description=description, snippets=snippets)}],
        )
        info = _extract_json(resp.content[0].text)
        info["spec_source"] = source
    except Exception as e:
        # An API failure here is fatal: the hardware budget is a HARD gate on which
        # models the run may even consider. Silently substituting
        # {usable_ram_mb: 3000, storage: 1500} would quietly change the feasible set and
        # every downstream selection, while the run still reported itself as
        # device-targeted. Stop instead.
        from agent.llm_errors import raise_if_fatal

        raise_if_fatal(e, "hardware_research")
        log(f"      [hw] LLM resolve returned unusable content ({e}); using conservative defaults.")
        info = {"device": description, "usable_ram_mb": 3000, "storage_budget_mb": 1500,
                "reference_chip": HW_FALLBACK_CHIP, "rationale": "fallback defaults",
                "spec_source": "defaults"}

    # reference_chip is device-specific (parsed from the description); fall back to
    # the configured anchor only when it cannot be resolved. latency/power/min_tok_s
    # are fixed system constants from config, not device-derived.
    ref = info.get("reference_chip")
    if ref not in KNOWN_CHIPS:
        ref = HW_FALLBACK_CHIP
    hw = HardwareConstraints(
        storage_mb=int(info.get("storage_budget_mb", 1500)),
        memory_mb=int(info.get("usable_ram_mb", 3000)),
        latency_ttft_ms=HW_LATENCY_TTFT_MS,
        power_watts=HW_POWER_WATTS,
        target_chip=ref,
        min_tok_s=HW_MIN_TOK_S,
    )
    log(f"      [hw] {info.get('device','?')} | {info.get('chipset','?')} | "
        f"RAM {info.get('ram_gb','?')}GB → usable {hw.memory_mb}MB | "
        f"model budget {hw.storage_mb}MB | ref_chip={hw.target_chip} "
        f"(source: {info.get('spec_source', '?')})")
    log(f"      [hw] rationale: {info.get('rationale','')}")
    return hw, info
