# agent/nodes/cold_start/hardware_research.py
"""
Autonomous hardware research.

Given a free-text device/chip description from the user, resolves it into a
HardwareConstraints object via a three-stage pipeline:

  1. LOCAL DB — fuzzy-match against data/devices.csv (Kaggle phone specs DB,
     generated by scripts/refresh_device_db.py). No API calls. Fast and free.
  2. EXA FALLBACK — if the device isn't in the local DB, use Exa web search
     to find spec snippets.
  3. LLM RESOLVE — Claude Sonnet interprets either local DB results or web
     snippets and emits a structured JSON with all hardware constraints.

Returns (HardwareConstraints, info_dict). info_dict is saved as device_research.json.
"""
import json
import os
import re

from config.android_pool import CHIP_SCALE_FACTORS, HardwareConstraints

REFERENCE_CHIPS = list(CHIP_SCALE_FACTORS.keys())

_DEVICES_CSV = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "devices.csv")

_PROMPT = """You are the hardware-analysis stage of an autonomous on-device fine-tuning agent. \
A user wants to run a small quantized language model on their phone. Given the user's device \
description and the device specs provided below, resolve the constraints \
that bound a deployable INT4 model.

Reply with ONLY a JSON object (no prose, no code fences) with keys:
- "device": resolved device name
- "chipset": the SoC (e.g. "Qualcomm Snapdragon 6 Gen 1")
- "ram_gb": integer total RAM
- "storage_gb": integer total storage
- "npu": short note on the NPU/AI accelerator, or null
- "usable_ram_mb": integer — RAM available to the model after OS/other apps (reserve ~2 GB on a phone)
- "storage_budget_mb": integer — a sensible on-disk budget for the model file (do NOT use the whole ROM; \
keep it small for efficient on-device use, typically 1000-3000 MB)
- "latency_ttft_ms": integer target time-to-first-token for interactive use (e.g. 2000)
- "power_watts": float sustained-inference power budget (e.g. 5.0)
- "reference_chip": the closest of {chips} to this device's SoC by performance tier
- "rationale": one sentence

User device description:
\"\"\"{description}\"\"\"

Device specs:
{snippets}
"""


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\n?", "", text)
        text = re.sub(r"\n?```$", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            raise ValueError(f"Hardware research did not return JSON: {text[:200]!r}")
        return json.loads(m.group())


def _lookup_local_db(description: str, log) -> str | None:
    """Fuzzy-match device name against the local Kaggle phone specs CSV.

    Returns a formatted string of matching rows, or None if no match or DB not found.
    """
    csv_path = os.path.abspath(_DEVICES_CSV)
    if not os.path.exists(csv_path):
        log("      [hw] Local device DB not found (run scripts/refresh_device_db.py to populate)")
        return None

    try:
        import csv
        # Extract search keywords from the description (device name words)
        desc_lower = description.lower()
        # Common device name keywords to search for
        keywords = [w for w in desc_lower.split()
                    if len(w) > 2 and w not in (
                        "the", "for", "and", "with", "that", "this", "run", "fine",
                        "tune", "small", "model", "ram", "rom", "storage", "deploy",
                        "deployment", "targeting", "efficiently", "should", "phone",
                        "smartphone", "device", "mobile",
                    )]

        matches = []
        with open(csv_path, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                device_name = (row.get("device") or "").lower()
                # Score: how many keywords appear in the device name
                score = sum(1 for kw in keywords if kw in device_name)
                if score >= 2:  # need at least 2 keyword matches
                    matches.append((score, row))

        if not matches:
            log(f"      [hw] No match in local DB for keywords: {keywords[:6]}")
            return None

        # Sort by score (descending), take top 3
        matches.sort(key=lambda x: -x[0])
        top = matches[:3]

        snippets = []
        for score, row in top:
            ram = row.get("ram_mb", "?")
            storage = row.get("storage_mb", "?")
            chipset = row.get("chipset", "?")
            snippets.append(
                f"- {row['device']}: RAM={ram}MB, Storage={storage}MB, Chipset={chipset}"
            )

        log(f"      [hw] Local DB matched {len(matches)} device(s), using top {len(top)}")
        return "\n".join(snippets)

    except Exception as e:
        log(f"      [hw] Local DB lookup failed ({e})")
        return None


def _exa_snippets(description: str, log) -> str:
    """Web search fallback via Exa API."""
    try:
        from config.config import EXA_API_KEY
        from exa_py import Exa
        exa = Exa(api_key=EXA_API_KEY)
        r = exa.search_and_contents(
            f"{description} smartphone chipset SoC RAM storage NPU full specifications",
            num_results=3, type="auto", text={"max_characters": 600},
        )
        return "\n".join(f"- {x.title[:80]}: {(x.text or '')[:300]}" for x in r.results)
    except Exception as e:
        log(f"      [hw] Exa lookup failed ({e}); proceeding from the description alone.")
        return "(no device specs available — resolve from the description text)"


def research_device(description: str, anthropic_client=None, log=print):
    """Resolve a device description into HardwareConstraints.

    Pipeline: local DB → Exa fallback → Claude LLM resolve.
    """
    if anthropic_client is None:
        import anthropic
        from config.config import ANTHROPIC_API_KEY
        anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY)

    from config.config import ORCHESTRATOR_MODEL

    # Stage 1: try local device DB first (no API cost)
    snippets = _lookup_local_db(description, log)
    source = "local_db"

    # Stage 2: Exa web search fallback
    if snippets is None:
        log("      [hw] Falling back to Exa web search...")
        snippets = _exa_snippets(description, log)
        source = "exa"

    # Stage 3: LLM resolve
    try:
        resp = anthropic_client.messages.create(
            model=ORCHESTRATOR_MODEL, max_tokens=700,
            messages=[{"role": "user", "content": _PROMPT.format(
                chips=REFERENCE_CHIPS, description=description, snippets=snippets)}],
        )
        info = _extract_json(resp.content[0].text)
        info["spec_source"] = source
    except Exception as e:
        log(f"      [hw] LLM resolve failed ({e}); using conservative defaults.")
        info = {"device": description, "usable_ram_mb": 3000, "storage_budget_mb": 1500,
                "latency_ttft_ms": 2000, "power_watts": 5.0,
                "reference_chip": "snapdragon_778g", "rationale": "fallback defaults",
                "spec_source": "defaults"}

    ref = info.get("reference_chip")
    if ref not in CHIP_SCALE_FACTORS:
        ref = "snapdragon_778g"
    hw = HardwareConstraints(
        storage_mb=int(info.get("storage_budget_mb", 1500)),
        memory_mb=int(info.get("usable_ram_mb", 3000)),
        latency_ttft_ms=int(info.get("latency_ttft_ms", 2000)),
        power_watts=float(info.get("power_watts", 5.0)),
        target_chip=ref,
    )
    log(f"      [hw] {info.get('device','?')} | {info.get('chipset','?')} | "
        f"RAM {info.get('ram_gb','?')}GB → usable {hw.memory_mb}MB | "
        f"model budget {hw.storage_mb}MB | ref_chip={hw.target_chip} "
        f"(source: {info.get('spec_source', '?')})")
    log(f"      [hw] rationale: {info.get('rationale','')}")
    return hw, info
