# agent/nodes/cold_start/hardware_research.py
"""
Autonomous hardware research.

Given a free-text device/chip description from the user, resolves it into a
HardwareConstraints object via a three-stage pipeline:

  1. LOCAL DB — fuzzy-match against data/devices.csv (Kaggle phone specs DB,
     generated by scripts/refresh_device_db.py). No API calls. Fast and free.
  2. EXA FALLBACK — if the device isn't in the local DB, use Exa web search
     to find spec snippets.
  3. LLM RESOLVE — the orchestrator model interprets either local DB results or web
     snippets and emits DEVICE-SPECIFIC values only: usable RAM, storage budget, and
     the reference chip. The remaining gates (latency, power, throughput floor) are
     fixed system constants from config.config (HW_*), not device-derived. The deployed
     model may be BF16, Q8_0, or Q4_K_M — nothing here assumes quantization.

Returns (HardwareConstraints, info_dict). info_dict is saved as device_research.json.
"""
import json
import os
import re

from agent.cost import tracked_anthropic_messages_create, tracked_exa_call
from agent.llm_text import MIN_THINKING_SAFE_MAX_TOKENS, response_text
from config.android_pool import KNOWN_CHIPS, HardwareConstraints

# Valid chipset vocabulary. Previously derived from CHIP_SCALE_FACTORS, a table of
# invented per-chip decode multipliers; KNOWN_CHIPS is just the names, no performance
# claims attached.
REFERENCE_CHIPS = list(KNOWN_CHIPS)

_DEVICES_CSV = os.path.join(os.path.dirname(__file__), "..", "..", "..", "data", "devices.csv")

_PROMPT = """You are the hardware-analysis stage of an autonomous on-device fine-tuning agent. \
A user wants to run a small language model on their phone. The deployed model MAY be full-precision \
(BF16) or quantized (Q8_0 / Q4_K_M) — do NOT assume it is quantized. Your ONLY job is to resolve \
how much RAM and storage the model may use on this device, from the device description and specs below.

YOU RESOLVE ONLY TWO VALUES — both are HARD gates on model selection:
- "usable_ram_mb": RAM available to the model at inference after the OS and foreground app. \
Any candidate variant whose PEAK RAM exceeds this is eliminated. Set it TOO LOW and every candidate \
is rejected (run fails); TOO HIGH and the chosen model out-of-memories on device. Typical Android \
OS + app footprint is ~1.5-2.0 GB, so usable ≈ total_RAM − 1500..2000 MB (e.g. 8 GB device → ~6000-6500 MB, \
6 GB → ~4000-4500 MB). Report the phone's TRUE usable RAM — a bigger budget is good, it lets the agent \
consider higher-quality (less-quantized) variants; the agent picks the smallest-RAM variant that still \
hits the accuracy goal on its own.
- "storage_budget_mb": on-disk weight-file budget. Full-precision (BF16) variants of ~3B models can \
exceed 6 GB on disk, so report the device's realistic free-storage allowance for a model file rather \
than an artificially small cap — under-reporting silently excludes the most capable variants.

You ALSO resolve "reference_chip" — the SoC governs decode speed, so it IS device-specific: \
map the device's chipset to the closest of {chips} by performance tier.

Everything else (latency target, power budget, decode-throughput floor) is a FIXED system constant \
configured elsewhere — do NOT output those; they are not device-specific.

Reply with ONLY a JSON object (no prose, no code fences) with keys:
- "device": resolved device name
- "chipset": the SoC (e.g. "Qualcomm Snapdragon 6 Gen 1"), or null if unknown
- "ram_gb": integer total RAM
- "storage_gb": integer total storage
- "usable_ram_mb": integer — RAM available to the model after OS/other apps (see guidance above)
- "storage_budget_mb": integer — on-disk model-file budget (see guidance above)
- "reference_chip": the closest of {chips} to this device's SoC by performance tier
- "rationale": one sentence covering how usable_ram_mb and storage_budget_mb were derived

User device description:
\"\"\"{description}\"\"\"

Device specs:
{snippets}
"""


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\n?", "", text)
        text = re.sub(r"\n?```$", "", text).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        m = re.search(r"\{.*\}", text, re.DOTALL)
        if not m:
            raise ValueError(f"Hardware research did not return JSON: {text[:200]!r}")
        return json.loads(m.group())


# --- Deterministic budget model -------------------------------------------------------------
# When the device IS in the CSV every number we need is already known, so there is nothing for an
# LLM to resolve — and letting it resolve anyway made the step non-reproducible (two runs on the
# identical S24 Ultra row produced storage budgets of 204,800 MB and 153,600 MB, a 33% swing in a
# hard gate on model selection). These constants make the same inputs always yield the same
# budgets. Override per-run if a target device behaves differently.
ANDROID_OS_OVERHEAD_MB = int(os.environ.get("SLM_HW_OS_OVERHEAD_MB", "2048"))
# Runtime cost beyond the weight file itself: KV cache, activations, tokenizer, llama.cpp/ORT
# arena and fragmentation headroom. Held out of the RAM budget so a variant that *just* fits its
# weights is not selected and then OOMs the moment it starts decoding.
INFERENCE_RUNTIME_OVERHEAD_MB = int(os.environ.get("SLM_HW_RUNTIME_OVERHEAD_MB", "1024"))
# Fraction of TOTAL storage a model file may occupy. Phones are rarely empty; this leaves room
# for the OS image, apps and user data without pretending the disk is free.
STORAGE_BUDGET_FRACTION = float(os.environ.get("SLM_HW_STORAGE_FRACTION", "0.60"))


def _deterministic_budgets(ram_mb: int, storage_mb: int) -> dict:
    """Derive the two hard gates from raw device specs, with no model call.

    usable_ram_mb = total RAM − OS/foreground overhead − inference runtime overhead
    storage_budget_mb = a fixed fraction of total storage
    """
    usable_ram = max(
        0, int(ram_mb) - ANDROID_OS_OVERHEAD_MB - INFERENCE_RUNTIME_OVERHEAD_MB
    )
    storage_budget = max(0, int(int(storage_mb) * STORAGE_BUDGET_FRACTION))
    return {
        "usable_ram_mb": usable_ram,
        "storage_budget_mb": storage_budget,
        "rationale": (
            f"deterministic: usable RAM = {int(ram_mb)}MB total "
            f"− {ANDROID_OS_OVERHEAD_MB}MB OS/foreground "
            f"− {INFERENCE_RUNTIME_OVERHEAD_MB}MB inference runtime (KV cache, activations, "
            f"allocator headroom) = {usable_ram}MB; storage budget = "
            f"{STORAGE_BUDGET_FRACTION:.0%} of {int(storage_mb)}MB = {storage_budget}MB"
        ),
    }


def _compact(value: str) -> str:
    """Lowercase, strip every non-alphanumeric character: 'Snapdragon 8 Gen 3' -> 'snapdragon8gen3'."""
    return re.sub(r"[^a-z0-9]+", "", str(value or "").lower())


def _closest_reference_chip(chipset: str) -> str | None:
    """Map a vendor chipset string onto a known reference chip, with no LLM call.

    Compares compacted forms so spacing and punctuation cannot defeat the match — the vendor
    writes "Qualcomm Snapdragon 8 Gen 3" while the reference id is "snapdragon_8gen3", which share
    only the token "snapdragon" and so failed a token-overlap test. Longest match wins, so
    'snapdragon_8gen3' is preferred over a shorter id that also happens to be a substring.
    """
    if not chipset:
        return None
    haystack = _compact(chipset)
    if not haystack:
        return None
    best = None
    for chip in REFERENCE_CHIPS:
        needle = _compact(chip)
        if needle and needle in haystack:
            if best is None or len(needle) > len(_compact(best)):
                best = chip
    return best


def _exact_local_device(description: str, log) -> dict | None:
    """Resolve the device fully deterministically when the CSV gives an unambiguous match.

    Returns a complete hardware dict (same shape the LLM path produces) or None to fall through
    to Exa + Claude research. Requires an unambiguous top match with usable RAM/storage/chipset —
    anything doubtful defers to the research path rather than guessing.
    """
    rows = _local_db_rows(description, log)
    if not rows:
        return None
    top_score, row = rows[0]
    # Ambiguous when a second candidate ties the top score: two different phones matched the
    # description equally well, so picking one silently would be a guess.
    if len(rows) > 1 and rows[1][0] == top_score:
        log(
            f"      [hw] Local DB match ambiguous ({row.get('device')!r} vs "
            f"{rows[1][1].get('device')!r} both scored {top_score}) — deferring to research"
        )
        return None
    try:
        ram_mb = int(float(row.get("ram_mb") or 0))
        storage_mb = int(float(row.get("storage_mb") or 0))
    except (TypeError, ValueError):
        return None
    if ram_mb <= 0 or storage_mb <= 0:
        log("      [hw] Local DB row missing RAM/storage — deferring to research")
        return None
    chipset = (row.get("chipset") or "").strip()
    reference_chip = _closest_reference_chip(chipset)
    if reference_chip is None:
        log(
            f"      [hw] Chipset {chipset!r} does not map to a known reference chip "
            "— deferring to research"
        )
        return None
    budgets = _deterministic_budgets(ram_mb, storage_mb)
    log(
        f"      [hw] EXACT local-DB hit: {row.get('device')} — resolved deterministically, "
        "no Exa/Claude call"
    )
    return {
        "device": row.get("device"),
        "chipset": chipset or None,
        "ram_gb": round(ram_mb / 1024),
        "storage_gb": round(storage_mb / 1024),
        "reference_chip": reference_chip,
        **budgets,
    }


def _local_db_rows(description: str, log) -> list[tuple[int, dict]]:
    """Scored CSV rows for the description, best first. Shared by both resolution paths."""
    snippets = _lookup_local_db(description, log, _return_rows=True)
    return snippets or []


def _lookup_local_db(description: str, log, _return_rows: bool = False):
    """Fuzzy-match device name against the local Kaggle phone specs CSV.

    Returns a formatted string of matching rows, or None if no match or DB not found.
    With ``_return_rows`` returns the scored ``(score, row)`` list instead, best first.
    """
    csv_path = os.path.abspath(_DEVICES_CSV)
    if not os.path.exists(csv_path):
        log("      [hw] Local device DB not found (run scripts/refresh_device_db.py to populate)")
        return None

    try:
        import csv
        # Extract search keywords from the description (device name words)
        desc_lower = description.lower()
        _STOP = {
            "the", "for", "and", "with", "that", "this", "run", "fine",
            "tune", "small", "model", "ram", "rom", "storage", "deploy",
            "deployment", "targeting", "efficiently", "should", "phone",
            "smartphone", "device", "mobile", "gb", "mb", "my", "using",
        }

        def _clean(tok: str) -> str:
            # strip surrounding punctuation ("9a," → "9a", "(2023)" → "2023")
            return tok.strip(".,;:()[]{}\"'").strip()

        keywords = []
        for w in (_clean(t) for t in desc_lower.split()):
            if not w or w in _STOP:
                continue
            has_digit = any(c.isdigit() for c in w)
            # Keep normal name words (len>2) AND short alphanumeric MODEL CODES that
            # contain a digit (e.g. "9a", "6a", "5g", "a14", "s24", "2023") — these are
            # the most discriminative tokens for a phone and were previously dropped by
            # the blanket len>2 rule, so single-distinctive-token phones (Pixel 6a,
            # Redmi 9A) never reached the >=2 match threshold. Drop pure memory sizes
            # like "2gb"/"128gb" (they don't appear in device names) and bare digits.
            if w.isdigit():
                # Keep short bare numbers — they are phone MODEL numbers ("12" in
                # "OnePlus 12", "8" in "Pixel 8") or years ("2023"). Only very long
                # digit runs (RAM/storage sizes already stripped of GB/MB) are dropped.
                if len(w) <= 4:
                    keywords.append(w)
                continue
            if w.endswith("gb") or w.endswith("mb"):
                continue
            if len(w) > 2 or has_digit:
                keywords.append(w)

        matches = []
        with open(csv_path, encoding="utf-8") as f:
            reader = csv.DictReader(f)
            for row in reader:
                device_name = (row.get("device") or "").lower()
                # Score: how many keywords appear in the device name
                score = sum(1 for kw in keywords if kw in device_name)
                if score >= 2:  # need at least 2 keyword matches
                    matches.append((score, row))

        if not matches:
            log(f"      [hw] No match in local DB for keywords: {keywords[:6]}")
            return [] if _return_rows else None

        # Sort by score (descending), take top 3
        matches.sort(key=lambda x: -x[0])
        if _return_rows:
            return matches
        top = matches[:3]

        snippets = []
        for score, row in top:
            ram = row.get("ram_mb", "?")
            storage = row.get("storage_mb", "?")
            chipset = row.get("chipset", "?")
            snippets.append(
                f"- {row['device']}: RAM={ram}MB, Storage={storage}MB, Chipset={chipset}"
            )

        log(f"      [hw] Local DB matched {len(matches)} device(s), using top {len(top)}")
        return "\n".join(snippets)

    except Exception as e:
        log(f"      [hw] Local DB lookup failed ({e})")
        return [] if _return_rows else None


def _exa_snippets(description: str, log) -> str:
    """Web search fallback via Exa API."""
    try:
        from config.config import EXA_API_KEY
        from exa_py import Exa
        exa = Exa(api_key=EXA_API_KEY)
        r = tracked_exa_call(
            exa.search_and_contents,
            f"{description} smartphone chipset SoC RAM storage NPU full specifications",
            stage="hardware_research",
            model="search-and-contents",
            num_results=3, type="auto", text={"max_characters": 600},
        )
        return "\n".join(f"- {x.title[:80]}: {(x.text or '')[:300]}" for x in r.results)
    except Exception as e:
        log(f"      [hw] Exa lookup failed ({e}); proceeding from the description alone.")
        return "(no device specs available — resolve from the description text)"


def research_device(description: str, anthropic_client=None, log=print):
    """Resolve a device description into HardwareConstraints.

    Pipeline: EXACT local DB hit → deterministic Python (no API calls at all).
              Otherwise: local DB snippets or Exa web search → Claude LLM resolve.

    The deterministic path exists because a CSV hit already contains every number needed; the
    LLM was only reformatting known data, and doing so non-reproducibly.
    """
    from config.config import (
        HW_LATENCY_TTFT_MS, HW_POWER_WATTS, HW_MIN_TOK_S, HW_FALLBACK_CHIP,
    )

    # Stage 0: fully deterministic resolution when the device is unambiguously in the CSV.
    exact = _exact_local_device(description, log)
    if exact is not None:
        exact["spec_source"] = "local_db_exact"
        return _finalize_hardware(exact, log)

    if anthropic_client is None:
        import anthropic
        from config.config import ANTHROPIC_API_KEY, orchestrator_client_kwargs
        anthropic_client = anthropic.Anthropic(api_key=ANTHROPIC_API_KEY, **orchestrator_client_kwargs())

    from config.config import ORCHESTRATOR_MODEL

    # Stage 1: partial/ambiguous local match — keep the rows as context for the LLM.
    snippets = _lookup_local_db(description, log)
    source = "local_db"

    # Stage 2: Exa web search fallback — ONLY when the device is not in the DB.
    if snippets is None:
        log("      [hw] Device not in local DB — falling back to Exa web search...")
        snippets = _exa_snippets(description, log)
        source = "exa"

    # Stage 3: LLM resolve — device-specific values only (RAM, storage, chip).
    try:
        resp = tracked_anthropic_messages_create(
            anthropic_client.messages,
            stage="hardware_research",
            model=ORCHESTRATOR_MODEL, max_tokens=MIN_THINKING_SAFE_MAX_TOKENS,
            messages=[{"role": "user", "content": _PROMPT.format(
                chips=REFERENCE_CHIPS, description=description, snippets=snippets)}],
        )
        info = _extract_json(response_text(resp))
        info["spec_source"] = source
    except Exception as e:
        # An API failure here is fatal: the hardware budget is a HARD gate on which
        # models the run may even consider. Silently substituting
        # {usable_ram_mb: 3000, storage: 1500} would quietly change the feasible set and
        # every downstream selection, while the run still reported itself as
        # device-targeted. Stop instead.
        from agent.llm_errors import raise_if_fatal

        raise_if_fatal(e, "hardware_research")
        log(f"      [hw] LLM resolve returned unusable content ({e}); using conservative defaults.")
        info = {"device": description, "usable_ram_mb": 3000, "storage_budget_mb": 1500,
                "reference_chip": HW_FALLBACK_CHIP, "rationale": "fallback defaults",
                "spec_source": "defaults"}

    return _finalize_hardware(info, log)


def _finalize_hardware(info: dict, log):
    """Turn a resolved spec dict into HardwareConstraints. Shared by both resolution paths."""
    from config.config import (
        HW_LATENCY_TTFT_MS, HW_POWER_WATTS, HW_MIN_TOK_S, HW_FALLBACK_CHIP,
    )

    # reference_chip is device-specific (parsed from the description); fall back to
    # the configured anchor only when it cannot be resolved. latency/power/min_tok_s
    # are fixed system constants from config, not device-derived.
    ref = info.get("reference_chip")
    if ref not in KNOWN_CHIPS:
        ref = HW_FALLBACK_CHIP
    hw = HardwareConstraints(
        storage_mb=int(info.get("storage_budget_mb", 1500)),
        memory_mb=int(info.get("usable_ram_mb", 3000)),
        latency_ttft_ms=HW_LATENCY_TTFT_MS,
        power_watts=HW_POWER_WATTS,
        target_chip=ref,
        min_tok_s=HW_MIN_TOK_S,
    )
    log(f"      [hw] {info.get('device','?')} | {info.get('chipset','?')} | "
        f"RAM {info.get('ram_gb','?')}GB → usable {hw.memory_mb}MB | "
        f"model budget {hw.storage_mb}MB | ref_chip={hw.target_chip} "
        f"(source: {info.get('spec_source', '?')})")
    log(f"      [hw] rationale: {info.get('rationale','')}")
    return hw, info
