"""GSM8K loader — grade-school math word problems with gold chain-of-thought.

Extracted from an inline converter inside `web_acquire.load_benchmark_dataset` on 2026-08-18, when
GSM8K was promoted to a first-class curated task. It was the last of the eight benchmarks whose row
construction lived in the autonomous-discovery module rather than in its own loader, which is why
it was also the only one with no registry entry and no stated instruction.

Row shape (shared with every generation-family task):

    {"text": <problem>, "answer": <final numeric answer>, "cot_reasoning": <gold working>,
     "label": "gsm8k", "_instruction": <the task instruction>}

The gold answer is the part of the dataset's `answer` field after the `####` marker; everything
before it is the worked solution, which is preserved as `cot_reasoning` rather than regenerated by
a teacher.
"""
from __future__ import annotations

HF_ID = "openai/gsm8k"
CONFIG = "main"
URL = f"https://huggingface.co/datasets/{HF_ID}"


def convert_gsm8k_rows(rows, instruction: str) -> list[dict]:
    """Shape raw GSM8K rows into the pipeline's row schema."""
    out: list[dict] = []
    for row in rows:
        question = str(row.get("question") or "").strip()
        raw = str(row.get("answer") or "")
        if not question or not raw:
            continue
        if "####" in raw:
            cot, _, final = raw.rpartition("####")
        else:
            cot, final = "", raw
        final = final.strip()
        if not final:
            continue
        out.append({
            "text": question,
            "answer": final,
            "cot_reasoning": cot.strip(),
            "label": "gsm8k",
            "_instruction": instruction,
        })
    return out


def load_gsm8k(
    max_train: int = 2000,
    max_test: int = 800,
    log=print,
    train_offset: int = 0,
) -> tuple[list[dict], list[dict]]:
    """Load GSM8K train/test.

    `train_offset` lets a mid-run `acquire` draw rows the curriculum has not already seen, rather
    than re-offering the same head slice and reporting zero novelty (B297).
    """
    from datasets import load_dataset

    from tasks.gsm8k import INSTRUCTION

    train_slice = f"train[{train_offset}:{train_offset + max_train}]"
    train = convert_gsm8k_rows(load_dataset(HF_ID, CONFIG, split=train_slice), INSTRUCTION)
    test = convert_gsm8k_rows(load_dataset(HF_ID, CONFIG, split=f"test[:{max_test}]"), INSTRUCTION)
    log(f"      [gsm8k] {len(train)} train (offset {train_offset}) / {len(test)} test rows")
    return train, test
