"""Grow the training curriculum, one `data_rebuild` at a time.

The curriculum is CUMULATIVE: cold start loads gold rows from the task's own loader, every rebuild
ADDS to what is already there, and rows leave only via quality control or the eval firewall. Two
mechanisms can add rows — `mine_new_real` and `surgical_synthesis` — and a plan names exactly one.

Nothing re-draws from a pool it has already drawn from. That was the gold FILL, removed on
2026-08-19: because the curriculum was rebuilt to a target size every iteration, something had to
refill it from the train pool, and with nothing else changed it re-selected the identical ~3,235 rows
and reported `0 novel` on eight consecutive rebuilds of run 38566712.
"""
from __future__ import annotations

import hashlib
import json
import os
import random
from collections import Counter
from collections.abc import Callable

from copy import deepcopy

from agent.checkpoint import atomic_write_jsonl
from agent.state import SKIPPED_NO_ROWS, AgentState
from data.curriculum import (
    annotate_cot,
    apply_quality_controls,
    synthesize_examples,
)
from data.loaders.dataset_integrity import normalize_text
from data.provenance import build_source_usage, source_key

# Per-row firewall reporting is bounded: a pathological rebuild could otherwise blocklist
# thousands of rows and bury the log in the very noise this reporting exists to replace.
_FIREWALL_LOG_LIMIT = int(os.environ.get("SLM_FIREWALL_LOG_LIMIT", "20"))


ARTIFACTS_DIR = "artifacts"

# One canonical name per rebuild KIND, keyed by the `_strategy_origin` each producer stamps on
# its rows. "data_rebuild" in a trajectory is ambiguous — a single rebuild runs the plan's
# strategy and then fills the rest of the curriculum from the train pool, and mining new real
# rows, targeting a confusion pair and drawing gold rows from the pool are three very different
# interventions with three different expected effects. Every rebuild names the kinds that actually
# contributed rows, so a log line stating `data_rebuild` always resolves to what ran.
#
# The names say what the producer DOES, because the previous ones did not. `resample-fill` read as
# a leftover of the removed `resample` STRATEGY when it is in fact the universal filler that
# supplies every curriculum's gold rows, and `fill-synth` was one character away from the
# `synth-fill` padding path that was deleted on 2026-08-16 — so the log appeared to be running a
# mechanism that no longer exists.
REBUILD_KIND_NAMES: dict[str, str] = {
    # Gold rows drawn from the run's existing real train pool. This is how EVERY curriculum is
    # assembled; it is not an orchestrator-selectable strategy — see agent/data_rebuild.py.
    "resample": "train-pool-gold",
    "mine_new_real_source": "mine-new-real",
    "surgical_synthesize": "surgical-synth",
    # Teacher-generated rows balanced across the label space, under the `synthesize` strategy.
    "synthesize": "balanced-synth",
}

# Row provenance tags that mean "this row was generated by the teacher", whichever path made it.
# The composition report used to count only "synthetic" (the plan's synthesize strategy), so
# generation-family positives were reported as unattributed and the dataset looked like it
# contained almost no synthetic data at all when most of the synthesis budget went there.
# `synthetic_fill` is retained ONLY so historical datasets and resumed checkpoints written before
# 2026-08-16 still count correctly; no code path produces it.
SYNTHETIC_PROVENANCE_TAGS = ("synthetic", "synthetic_fill", "synthetic_positive")

# Row provenance tags that mean "this row is real, human-authored data from the train pool".
# Kept next to the synthetic tags because `n_gold` is defined as their sum.
GOLD_PROVENANCE_TAGS = ("train_anchor", "resample")


def rebuild_kind_name(strategy_origin: str) -> str:
    """Canonical human name for a rebuild sub-strategy, for logs and artifacts."""
    return REBUILD_KIND_NAMES.get(str(strategy_origin), str(strategy_origin))


def _task_spec(state: AgentState):
    """The spec for the task this run is training."""
    from tasks import get_task

    return get_task(state["task"])


def _pinned_label_space(state: AgentState) -> set[str] | None:
    """The run's closed label vocabulary, pinned by eval_setup from the frozen eval set.

    Falls back to deriving it from the eval set directly, so a resumed checkpoint written before
    the field existed still gets the guarantee rather than silently reverting to the old behaviour.
    """
    pinned = state.get("task_label_space")
    if isinstance(pinned, dict) and pinned.get("labels"):
        return {str(label) for label in pinned["labels"]}
    from data.label_space import label_space_from_eval_set

    return label_space_from_eval_set(state.get("eval_set"), state["task"])


# Absolute floor on curriculum size. Synth-fill used to guarantee the curriculum reached its target;
# with it gone, the size is whatever real data supplies, and a task whose loader silently returns
# almost nothing would otherwise train on it and report a meaningless score. 500 is a floor on
# *viability*, not a target: there is no target, and a curriculum this small means the
# loader returned almost nothing rather than that a rebuild underdelivered.
MIN_CURRICULUM_ROWS = int(os.environ.get("SLM_MIN_CURRICULUM_ROWS", "500"))


def _populated_difficulty_buckets(state: AgentState, model_id: str) -> set[str] | None:
    """Which difficulty buckets actually contain eval rows, or None if unknown.

    A bucket can be structurally empty. The buckets come from a two-model capability gradient
    (`test_agent.label_difficulty`): `easy` = both the smallest and largest model pass, `medium` =
    only the largest passes, `hard` = neither. On a format-bound task neither model can produce the
    output contract zero-shot, so nothing separates them and `medium` is empty for the whole run —
    which is what happened on BC5CDR, where the orchestrator was nonetheless handed `medium=0.25`
    and spent a quarter of its curriculum budget on rows that do not exist (B275).
    """
    difficulty = state.get("eval_difficulty")
    if not isinstance(difficulty, dict) or not difficulty:
        return None
    populated = {
        bucket
        for bucket in ("easy", "medium", "hard")
        if difficulty.get(bucket)
    }
    if not populated:
        return None
    empty = [b for b in ("easy", "medium", "hard") if b not in populated]
    if empty:
        _log(
            model_id,
            f"  Difficulty buckets present: "
            + ", ".join(f"{b}={len(difficulty.get(b) or [])}" for b in populated)
            + f" — EMPTY: {', '.join(empty)}. Their curriculum weight is redistributed to the "
            f"populated buckets, because weighting a bucket with no eval rows spends budget on "
            f"nothing.",
        )
    return populated


def _enforce_curriculum_floor(dataset: list[dict], *, model_id: str, target_rows: int) -> None:
    """Fail loudly when real data cannot supply a viable curriculum.

    Raises rather than warning: below this point the run would burn GPU hours producing a number
    nobody should trust, and the cause is always upstream (a loader returning almost nothing, or
    quality control removing nearly everything) where it can actually be fixed.
    """
    if len(dataset) >= MIN_CURRICULUM_ROWS:
        return
    raise RuntimeError(
        f"curriculum has only {len(dataset)} row(s), below the {MIN_CURRICULUM_ROWS}-row floor "
        f"(target was {target_rows}). Synth-fill no longer pads to target, so this means the real "
        f"data genuinely is not there. Check the loader's train split and the [qc] removals above; "
        f"override the floor with SLM_MIN_CURRICULUM_ROWS if this is deliberate."
    )


def _label_definitions(state: AgentState) -> dict | None:
    """What each class MEANS, for the synthesis and verification prompts.

    Pinned by eval_setup. Without it the teacher judges the label's wording rather than the task:
    on RouterBench, where `local` means "a small model can answer this", it rejected 70% of
    generated rows with verdicts like "the utterance is a math problem, not a local query" (B267).
    """
    pinned = state.get("task_label_space")
    if isinstance(pinned, dict) and pinned.get("definitions"):
        return dict(pinned["definitions"])
    return None


def _log(model_id: str, message: str) -> None:
    print(f"[curate][{model_id}] {message}")


def _entropy_seed() -> int:
    """A fresh, non-deterministic seed per sampler call (redesign 2026-07-31).

    Curation is deliberately NON-deterministic: each reshuffle/synthesis draw uses real
    OS entropy so repeated rebuilds genuinely vary run to run. There is no plan-identity
    seed and no reproducibility guarantee across checkpoint resumes.
    """
    return int.from_bytes(os.urandom(8), "big")


def _verifier_for(task: str, state: AgentState):
    """Return an EXACT, programmatic correctness verifier for synthetic rows, or None.

    This is the first of two gates on generated rows, and it runs BEFORE the model-based pass:

        generate → programmatic verify (exact, free) → model verify (judgement) → quality control

    For `function_call` (xLAM/BFCL) and `calendar_json` the check is pure computation — parse the
    JSON, confirm the call targets a DECLARED tool with arguments its schema actually has, and for
    calendar additionally that the datetimes parse, that end follows start, that the duration matches
    the stated convention, and that the date sits near the request's own reference instant. See
    `data/synth_verifiers.py`.

    None is the honest answer elsewhere: summarisation quality is not decidable by computation, and
    classification/NER rows inherit a real anchor's label so there is no answer to verify — they get
    the teacher label-verification pass instead.
    """
    from tasks import get_task

    return get_task(task).synth_verifier


def _row_text(row: dict) -> object:
    return row.get("text", row.get("prompt", ""))


def _normalized_eval_texts(eval_set) -> set[str]:
    if eval_set is None:
        return set()
    rows = getattr(eval_set, "all", [])
    if not isinstance(rows, (list, tuple)):
        return set()
    texts = {
        normalize_text(_row_text(row))
        for row in rows
        if isinstance(row, dict)
    }
    texts.discard("")
    return texts


def _exclude_eval_rows(
    rows: list[dict],
    eval_set,
    *,
    tally: dict | None = None,
    layer: str | None = None,
    log=None,
) -> tuple[list[dict], int]:
    """Apply the normalized-text eval firewall to candidate training rows.

    When ``tally`` is provided, the number of rows removed at this ``layer`` is accumulated into
    it (creating the key at 0 even when nothing is removed) so a run can durably report firewall
    activity per iteration — including the healthy zero-drop case.

    When ``log`` is provided, each blocked row is reported with its reason and a short redacted
    fingerprint of the offending text. There is exactly one reason a row is blocked here — its
    normalized text is byte-identical to a held-out eval row — but stating it per row means an
    operator can see WHICH rows leaked instead of only a count. The text is truncated and the
    match is reported as a hash so held-out eval content never lands in the run log.
    """
    eval_texts = _normalized_eval_texts(eval_set)
    if tally is not None and layer is not None:
        tally.setdefault(layer, 0)
    if not eval_texts:
        return list(rows), 0
    clean = []
    blocked = []
    for row in rows:
        if isinstance(row, dict) and normalize_text(_row_text(row)) in eval_texts:
            blocked.append(row)
        else:
            clean.append(row)
    removed = len(blocked)
    if tally is not None and layer is not None:
        tally[layer] = tally.get(layer, 0) + removed
    if log and blocked:
        for row in blocked[:_FIREWALL_LOG_LIMIT]:
            normalized = normalize_text(_row_text(row))
            digest = hashlib.sha256(normalized.encode("utf-8")).hexdigest()[:8]
            log(
                f"    [firewall:{layer or 'unknown'}] BLOCKED row "
                f"(provenance={row.get('_provenance') or 'unknown'}, "
                f"label={row.get('label') or 'n/a'}, len={len(normalized)} chars, "
                f"text_sha8={digest}): normalized text exactly matches a held-out eval row, "
                "so training on it would leak the eval set"
            )
        if removed > _FIREWALL_LOG_LIMIT:
            log(
                f"    [firewall:{layer or 'unknown'}] ... and "
                f"{removed - _FIREWALL_LOG_LIMIT} more blocked for the same reason"
            )
    return clean, removed


def _read_jsonl(path: str | None) -> list[dict]:
    if not path or not os.path.isfile(path):
        return []
    with open(path, encoding="utf-8") as source:
        return [
            value
            for line in source
            if line.strip()
            for value in [json.loads(line)]
            if isinstance(value, dict)
        ]


def _normalized_texts(rows: list[dict]) -> set[str]:
    values = {
        normalize_text(_row_text(row))
        for row in rows
        if isinstance(row, dict)
    }
    values.discard("")
    return values


def _label_key(row: dict, task: str) -> str:
    """The value a row is grouped by for balance reporting and round-robin sampling.

    A row with no `label` is grouped by its first entity type when it has entities — that is how
    span tasks get a meaningful histogram — and otherwise by a single bucket.
    """
    label = row.get("label")
    if label is not None:
        return str(label)
    entity_types = [
        str(entity.get("type", "?"))
        for entity in row.get("entities", []) or []
        if isinstance(entity, dict)
    ]
    return entity_types[0] if entity_types else "no_entity"


def _source_key(row: dict, default: str = "unknown") -> str:
    value = row.get("_source")
    if value:
        return str(value)
    record = row.get("_source_record")
    if isinstance(record, dict):
        return (
            f"{record.get('kind', 'source')}:{record.get('id', '?')}"
            f"/{record.get('split', 'train')}"
        )
    return default


def _round_robin_sample(
    rows: list[dict],
    *,
    count: int,
    key: Callable[[dict], str],
    seed: int,
) -> list[dict]:
    groups: dict[str, list[dict]] = {}
    for row in rows:
        groups.setdefault(key(row), []).append(row)
    rng = random.Random(seed)
    for values in groups.values():
        rng.shuffle(values)
    names = sorted(groups)
    selected: list[dict] = []
    while len(selected) < count and any(groups.values()):
        for name in names:
            if groups[name] and len(selected) < count:
                selected.append(groups[name].pop())
    return selected


def _balanced_sample(
    rows: list[dict],
    *,
    count: int,
    task: str,
    seed: int,
) -> list[dict]:
    if count <= 0:
        return []
    from tasks import get_task

    # Round-robin across classes only where classes exist and every one matters. A task with no
    # closed label space has nothing to round-robin over.
    if get_task(task).closed_label_space:
        return _round_robin_sample(
            rows,
            count=min(count, len(rows)),
            key=lambda row: _label_key(row, task),
            seed=seed,
        )
    shuffled = list(rows)
    random.Random(seed).shuffle(shuffled)
    return shuffled[:count]


def _tag_train_rows(
    rows: list[dict],
    *,
    default_source: str,
) -> list[dict]:
    tagged = []
    for row in rows:
        value = dict(row)
        value.setdefault("_provenance", "train_anchor")
        value.setdefault("_source", default_source)
        tagged.append(value)
    return tagged


def _tag_mined_rows(rows: list[dict]) -> list[dict]:
    return [
        {
            **row,
            "_provenance": "mined_real",
            "_strategy_origin": "mine_new_real_source",
        }
        for row in rows
    ]


def _merge_persistent_train_rows(
    existing_rows: list[dict],
    mined_rows: list[dict],
    eval_set,
    *,
    tally: dict | None = None,
) -> list[dict]:
    """Retain novel real rows for every later rebuild and checkpoint."""
    candidates, _ = _exclude_eval_rows(
        [*existing_rows, *mined_rows],
        eval_set,
        tally=tally,
        layer="persistent_merge",
    )
    merged = []
    seen = set()
    for row in candidates:
        if not isinstance(row, dict):
            continue
        text = normalize_text(_row_text(row))
        if not text or text in seen:
            continue
        seen.add(text)
        merged.append(dict(row))
    return merged


# Per-category caps. Surgical synthesis exists to concentrate teacher calls where the model is
# losing points, so the per-category share is proportional to that category's failure count — but
# bounded, because a single dominant category should not consume a whole rebuild and a category with
# two failures does not justify a hundred rows.
SURGICAL_MAX_CATEGORIES = int(os.environ.get("SLM_SURGICAL_MAX_CATEGORIES", "5"))
SURGICAL_MIN_ROWS_PER_CATEGORY = 25
SURGICAL_MAX_ROWS_PER_CATEGORY = 600


def _eligible_categories(state: AgentState, plan: dict, model_id: str) -> list[dict]:
    """The failure categories worth spending this rebuild on.

    Categories come from the task's own failure taxonomy via the test report, so they name something
    the scorer measured — `wrong_arguments`, `unparseable_output`, a real class confusion — rather
    than a channel-wide constant. Under the old design every open-ended task reported the single
    literal `gold_verifier -> incorrect`, whose count is the failure count the orchestrator already
    had, and it wrote pages of reasoning about that constant (B296).

    A category already targeted whose count did not fall is EXHAUSTED and skipped: without that
    check the run keeps pouring rows at something that is not responding, which is the loop the
    CLINC150 run got stuck in (B224).
    """
    requested = [
        entry for entry in (plan.get("target_categories") or [])
        if isinstance(entry, dict) and entry.get("category")
    ]
    if not requested:
        report = state.get("test_report") or {}
        requested = [
            {"category": str(pair.get("gold")), "count": int(pair.get("count", 0) or 0)}
            for pair in (report.get("confusion_pairs") or [])
            if isinstance(pair, dict) and pair.get("gold")
        ]
    history = dict(state.get("surgical_category_history") or {})
    eligible: list[dict] = []
    for entry in sorted(requested, key=lambda e: -int(e.get("count", 0) or 0)):
        category = str(entry["category"])
        count = int(entry.get("count", 0) or 0)
        previous = history.get(category)
        if previous is not None and count >= int(previous.get("count_when_targeted", 0)):
            _log(
                model_id,
                f"  [surgical] SKIP {category}: targeted before at count="
                f"{previous.get('count_when_targeted')}, still {count} — EXHAUSTED, "
                "spending elsewhere",
            )
            continue
        eligible.append({"category": category, "count": count})
        if len(eligible) >= SURGICAL_MAX_CATEGORIES:
            break
    return eligible


def _anchor_pool(state: AgentState, category: str, train_rows: list[dict]) -> list[dict]:
    """Real rows to anchor generation on for `category`.

    For a task with a closed label space the category IS a class, so anchoring on that class's own
    rows conveys its phrasing and length distribution. For everything else there is no class to
    anchor on — the category names an error KIND — so the whole pool is eligible and the category is
    carried into the prompt as a steer instead.
    """
    if not _task_spec(state).closed_label_space:
        return train_rows
    same_class = [
        row for row in train_rows
        if isinstance(row, dict) and str(row.get("label")) == category
    ]
    return same_class or train_rows


def _surgical_synthesize(
    state: AgentState,
    plan: dict,
    train_rows: list[dict],
    *,
    model_id: str,
    eval_set=None,
) -> list[dict]:
    """Generate rows aimed at the failure categories costing the most points.

    This is now the ONLY synthesis path. The balanced label-space fill it replaced spent most of the
    teacher budget on rows chosen for class balance rather than for anything the model was getting
    wrong, and on `function_call` it produced nothing at all for six consecutive rebuilds because the
    task matched no dispatch branch (B291).

    Generated rows are gated twice: by the task's exact programmatic verifier where one exists
    (xlam, calendar, NER — free, unfoolable) and by the teacher's own check of its own output
    otherwise. Both are told what the task is via the orchestrator-authored brief.
    """
    if not train_rows:
        _log(model_id, "  [surgical] no anchor rows available; nothing to generate from")
        return []
    if os.environ.get("SLM_CHEAP") == "1":
        _log(model_id, "  [surgical] CHEAP MODE: synthesis skipped")
        return []

    from data.synth_client import get_generate_fn, wait_until_available

    logger = lambda message: _log(model_id, message)
    if not wait_until_available(log=logger):
        _log(model_id, "  [surgical] synthesis endpoint unavailable — no rows generated")
        return []
    generate = get_generate_fn(log=logger)

    eligible = _eligible_categories(state, plan, model_id)
    if not eligible:
        _log(
            model_id,
            "  [surgical] no failure category to target: the last eval reported no categorised "
            "failures, so there is no evidence to aim at. Nothing generated.",
        )
        return []

    spec = _task_spec(state)
    brief = state.get("task_brief")
    total_budget = int(plan["rows"])
    total_count = sum(entry["count"] for entry in eligible) or len(eligible)
    history = dict(state.get("surgical_category_history") or {})
    out: list[dict] = []
    # Boxed so the per-category loop can accumulate into it; the caller needs the attempted count to
    # tell "the generator produced nothing" from "verification rejected everything".
    attempted_total = [0]

    for entry in eligible:
        category, count = entry["category"], entry["count"]
        share = int(round(total_budget * (count or 1) / total_count))
        share = max(SURGICAL_MIN_ROWS_PER_CATEGORY,
                    min(share, SURGICAL_MAX_ROWS_PER_CATEGORY))
        pool = _anchor_pool(state, category, train_rows)
        anchors = _balanced_sample(
            pool, count=min(share, len(pool)), task=state["task"], seed=_entropy_seed(),
        )
        if not anchors:
            continue
        _log(
            model_id,
            f"  ▶ SURGICAL SYNTHESIS [{category}]: {count} failure(s) → generating up to "
            f"{len(anchors)} row(s) "
            f"({'exact+teacher' if spec.synth_verifier else 'teacher-verified only'})",
        )
        rows = synthesize_examples(
            anchors,
            task=state["task"],
            n=len(anchors),
            generate_fn=generate,
            verify_fn=spec.synth_verifier,
            log=logger,
            label_definitions=_label_definitions(state),
            brief=brief,
            target_category=category,
        )
        kept = [
            {**row, "_provenance": "synthetic", "_strategy_origin": "surgical_synthesis",
             "_target_category": category}
            for row in rows
            if isinstance(row, dict)
        ]
        _log(model_id, f"    [{category}] kept {len(kept)} of {len(anchors)} attempted")
        attempted_total[0] += len(anchors)
        out.extend(kept)
        history[category] = {
            "count_when_targeted": count,
            "iteration": int(state.get("iteration", 0) or 0),
            "rows_generated": len(kept),
        }

    state["surgical_category_history"] = history
    state["_last_synth_attempted"] = attempted_total[0]
    state["_last_synth_kept"] = len(out)
    _archive_synthetic_rows(state, out, model_id=model_id)
    return out


def _archive_synthetic_rows(state: AgentState, rows: list[dict], *, model_id: str) -> None:
    """Append what synthesis produced — rows it KEPT and a sample of rows it REJECTED — to an audit file.

    The versioned `dataset_vN.jsonl` artifacts are the curriculum, and rollback overwrites them: on
    run 38708719 both synthesis rounds regressed, were rolled back, and the next mining round wrote a
    new `dataset_v2`, so afterwards not one synthesized row survived anywhere on disk. The rows could
    not be inspected to ask WHY they hurt — which is the single most useful question about them, and
    the orchestrator had already concluded twice that they carry noise.

    REJECTED rows are archived for the same reason, and the omission was worse. This function used to
    return early on an empty list, so a rebuild that kept nothing wrote nothing — meaning the audit
    trail went silent in precisely the case with the most to explain. Run 38985393 generated 519
    toolbench rows, the verifier rejected all 519, and afterwards there was no way to see what the
    teacher had actually written. Each rejected row carries `_reject_reason`, so the file answers both
    "which check refused it" and "what did the text look like".

    Append-only and never read back by the pipeline. It is evidence, not state.
    """
    from data.curriculum import take_rejected_rows

    rejected = take_rejected_rows()
    if not rows and not rejected:
        return
    try:
        import json as _json

        iteration = int(state.get("iteration", 0) or 0) + 1
        path = os.path.join(ARTIFACTS_DIR, "synthetic_rows_audit.jsonl")
        os.makedirs(os.path.dirname(path), exist_ok=True)
        with open(path, "a", encoding="utf-8") as handle:
            for verdict, batch in (("kept", rows), ("rejected", rejected)):
                for row in batch:
                    handle.write(_json.dumps({
                        "_iteration": iteration,
                        "_verdict": verdict,
                        **{k: v for k, v in row.items()},
                    }, ensure_ascii=False) + "\n")
        note = f"  [synth] archived {len(rows)} kept"
        if rejected:
            note += f" and {len(rejected)} rejected (sampled)"
        _log(model_id, f"{note} row(s) to {os.path.basename(path)} "
                       f"(survives rollback, for auditing what synthesis produced)")
    except Exception as error:  # noqa: BLE001 — an audit trail must never break a rebuild
        _log(model_id, f"  [synth] could not archive generated rows "
                       f"({type(error).__name__}: {error})")


def _cot_applies(task: str) -> bool:
    """Whether a teacher-authored chain of thought earns its one call per row.

    CoT pays for itself when the gold answer is the END of a multi-step derivation the model
    has to reason its way to: `math_reasoning` and `code_generation` qualify by definition.

    The `generation` family does NOT qualify by default, because it also covers single-step
    rewrites. Dialogue summarization is the case that forced this distinction: the summary is
    a compression of text already sitting in the prompt, not the conclusion of an argument, so
    a reasoning chain adds nothing the model cannot read off its own input — while costing one
    teacher call for EVERY row, which was over half the synthesis budget of a DialogSum/SAMSum
    curate pass. Set SLM_COT_GENERATION=1 for a genuinely multi-step `generation` dataset such
    as open-domain QA.
    """
    from tasks import get_task

    return get_task(task).cot_annotation


def _annotate_generation_cot(
    rows: list[dict],
    state: AgentState,
    *,
    model_id: str,
) -> list[dict]:
    task = state["task"]
    if not _cot_applies(task):
        _log(
            model_id,
            f"  Skipping CoT annotation: {task} declares cot_annotation=False",
        )
        return rows
    if os.environ.get("SLM_CHEAP") == "1":
        _log(model_id, "  CHEAP MODE: skipping CoT annotation")
        return rows
    from config.config import SYNTH_API_MODE, SYNTH_MODEL
    from data.synth_client import get_generate_fn, is_available

    logger = lambda message: _log(model_id, message)
    generate = get_generate_fn(log=logger) if is_available(log=logger) else None
    _log(
        model_id,
        f"  CoT annotation: teacher={'API' if SYNTH_API_MODE else 'LOCAL'} {SYNTH_MODEL} "
        f"({'available' if generate is not None else 'unavailable — skipping CoT'})"
        + ("  — one PAID call per row" if SYNTH_API_MODE else ""),
    )
    return annotate_cot(
        rows,
        generate_fn=generate,
        log=logger,
    )


def _log_dataset_report(
    model_id: str,
    dataset: list[dict],
    *,
    task: str,
    provenance: dict[str, int],
) -> None:
    label_dist = Counter(_label_key(row, task) for row in dataset)
    lengths = [len(str(_row_text(row))) for row in dataset]
    mean_length = sum(lengths) / len(lengths) if lengths else 0
    median_length = sorted(lengths)[len(lengths) // 2] if lengths else 0
    _log(model_id, "  ┌─ Dataset report ─────────────────────────")
    _log(model_id, f"  │ Total examples : {len(dataset)}")
    _log(model_id, f"  │ Provenance     : {dict(provenance)}")
    _log(model_id, f"  │ Labels         : {dict(label_dist)}")
    _log(
        model_id,
        f"  │ Text length    : mean={mean_length:.0f} median={median_length}",
    )
    _log(model_id, "  └────────────────────────────────────────────")


def _dedupe_into(
    curriculum: list[dict],
    additions: list[dict],
) -> tuple[list[dict], int]:
    """Append only the additions whose normalized text is not already present.

    Returns ``(new_curriculum, n_added)``. This is the ONLY place the curriculum grows, and the
    only deduplication mining needs: "overlap between two sets of training rows" is just a
    duplicate, and a duplicate is dropped here. Overlap with the HELD-OUT EVAL SET is a different
    concern entirely and is handled by `_exclude_eval_rows`.
    """
    existing = _normalized_texts(curriculum)
    out = list(curriculum)
    added = 0
    for row in additions:
        text = normalize_text(_row_text(row))
        if text and text in existing:
            continue
        out.append(dict(row))
        if text:
            existing.add(text)
        added += 1
    return out, added


# The most rows ONE mine_new_real rebuild may add, whatever the plan asked for and whatever the source
# holds. Two reasons, and the second is the load-bearing one:
#
#   * growth stays legible. A rebuild that adds a few hundred rows is an experiment whose effect can be
#     read off the next eval; one that adds three thousand changes the curriculum, the training time
#     and the class balance at once, and the score movement cannot be attributed to any of them. Run
#     38661753 asked for 600 rows and added 2,399, then asked for 800 and added 3,161.
#   * a finite source lasts. xLAM holds ~60,000 rows. At 3,000 a rebuild it is exhausted in twenty
#     iterations and the mining ladder falls through to synthesis with most of the corpus unread.
#
# Rows beyond the ceiling are NOT discarded: `source_progress` advances only by what was consumed, so
# the next rebuild continues from where this one stopped. That is what makes a newly discovered dataset
# worth keeping rather than draining in one pass.
MAX_MINED_ROWS_PER_REBUILD = int(os.environ.get("SLM_MAX_MINED_ROWS_PER_REBUILD", "1000"))


def _reread_known_sources(
    state: AgentState,
    *,
    want: int,
    model_id: str,
) -> tuple[list[dict], list[str]]:
    """Re-read the task's own datasets for rows the curriculum has not taken yet.

    The cheapest possible source of new real data, and for most of this suite the only honest one.
    Every loader takes a head slice of its split, so asking for a LARGER slice returns a superset
    and everything past what we already consumed is novel by construction — no provider call, no
    LLM column mapping, no schema risk.

    This is what did not exist before 2026-08-19: `acquire` went straight to paid web discovery,
    which then found mirrors of the very corpus sitting in the local cache and rejected them, while
    ~57,000 unused xLAM rows stayed unreachable (B297).

    Returns ``(rows, exhausted_source_ids)``.
    """
    spec = _task_spec(state)
    progress = dict(state.get("source_progress") or {})
    rows: list[dict] = []
    newly_exhausted: list[str] = []
    # Boxed so the per-source loop can spend it: the ceiling is per REBUILD, not per source, or three
    # sources would together deliver three times the cap.
    remaining_budget = [MAX_MINED_ROWS_PER_REBUILD]
    for source in spec.mining_sources:
        record = dict(progress.get(source.hf_id) or {})
        if record.get("exhausted"):
            continue
        consumed = int(record.get("consumed", 0) or 0)
        # Ask for the slice we intend to KEEP, not a multiple of it. Everything past `consumed` is
        # novel by construction (see the docstring), so the only losses downstream are the eval
        # firewall and quality control — about 1% in practice.
        #
        # This was `want * 4`, which over-delivered fourfold because nothing trimmed the surplus.
        # Trimming afterwards is NOT the fix and was tried: `consumed` records the slice depth READ, so
        # discarding the surplus advances the pointer past rows that were never used and silently skips
        # them for the rest of the run. Asking for the right amount is the fix — the pointer and the
        # rows then agree.
        take = min(max(want, 1), remaining_budget[0])
        if take <= 0:
            break
        ask = consumed + take
        try:
            more_train, _more_eval = spec.load(max_train=ask, max_test=60)
        except Exception as error:  # noqa: BLE001 — one bad source must not stop the rebuild
            _log(model_id, f"  [mine] re-read of {source.hf_id} FAILED "
                           f"({type(error).__name__}: {error})")
            continue
        returned = len(more_train)
        novel = more_train[consumed:] if returned > consumed else []
        record.update({"consumed": max(consumed, returned), "asked_for": ask,
                       "url": source.url})
        remaining_budget[0] -= len(novel)
        # Fewer rows than we asked for is the only reliable evidence a head slice has hit the end
        # of the split. Equal-to-asked means there is probably more.
        if returned < ask:
            record["exhausted"] = True
            newly_exhausted.append(source.hf_id)
        progress[source.hf_id] = record
        # Only the rows past the previous high-water mark. Returning the whole slice made every
        # re-read hand back rows the curriculum already had and rely on downstream dedup to notice.
        rows.extend(novel)
        _log(model_id,
             f"  [mine] re-read {source.hf_id}: slice {consumed}→{returned}, "
             f"{len(novel)} new row(s) (per-rebuild ceiling {MAX_MINED_ROWS_PER_REBUILD}, "
             f"{max(0, remaining_budget[0])} left)"
             + (" — source EXHAUSTED" if record.get("exhausted") else ""))
    state["source_progress"] = progress
    return rows, newly_exhausted


def _register_discovered_source(
    state: AgentState,
    discovery_report: dict,
    *,
    taken: int,
    model_id: str,
) -> None:
    """Record a web-discovered dataset so later rebuilds can read more of it.

    `source_progress` is keyed by dataset id and consulted by `_reread_known_sources`, which is rung 1
    of the mining ladder — the free rung. Writing the discovery there converts a one-off paid lookup
    into a source the run can return to, which is the difference between discovery being worth doing
    once and worth doing at all.

    `consumed` is set to the number of rows this rebuild actually TOOK, not the number the provider
    returned, so the next re-read resumes at the first unused row rather than skipping the remainder.
    """
    dataset_id = str(
        discovery_report.get("dataset")
        or discovery_report.get("hf_id")
        or discovery_report.get("source")
        or ""
    ).strip()
    if not dataset_id:
        _log(model_id, "  [mine] discovery did not name a dataset id, so it cannot be recorded for "
                       "re-reading; the next rebuild will have to discover a source again")
        return
    progress = dict(state.get("source_progress") or {})
    record = dict(progress.get(dataset_id) or {})
    record.update({
        "consumed": int(record.get("consumed", 0) or 0) + taken,
        "url": discovery_report.get("url") or record.get("url") or "",
        "discovered": True,
    })
    progress[dataset_id] = record
    state["source_progress"] = progress
    # Also add it to the run's live source list so rung 1 actually visits it next time.
    discovered_sources = list(state.get("discovered_sources") or [])
    if dataset_id not in discovered_sources:
        discovered_sources.append(dataset_id)
        state["discovered_sources"] = discovered_sources
    _log(model_id, f"  [mine] recorded {dataset_id} at {record['consumed']} row(s) consumed — the "
                   f"next mine_new_real rebuild re-reads it from there for free")


def _discover_new_source(
    state: AgentState,
    *,
    want: int,
    model_id: str,
    eval_set,
) -> tuple[list[dict], dict]:
    """Last rung of the mining ladder: web research for a dataset we have never used.

    Only reached once every known source is exhausted. The orchestrator judges whether a candidate
    is a fit and maps its columns onto our schema; rows that do not map, or whose label falls
    outside a closed vocabulary, are dropped PER ROW rather than causing the whole source to be
    rejected.
    """
    from data.loaders.web_acquire import mine_additional_real_rows

    spec = _task_spec(state)
    if not spec.allow_paid_discovery:
        _log(model_id, f"  [mine] {spec.name} does not permit web discovery; no new sources to try")
        return [], {"status": "not_permitted"}

    task_plan = dict(state.get("task_plan") or {})
    task_plan.setdefault("task_name", spec.title)
    task_plan.setdefault("benchmark", spec.name)
    pinned = _pinned_label_space(state)
    if pinned:
        task_plan["labels"] = sorted(pinned)
    brief = state.get("task_brief") or {}
    description = str(brief.get("summary") or spec.title)

    rows, report = mine_additional_real_rows(
        label_space=pinned,
        task_plan=task_plan,
        description=description,
        task=spec.name,
        existing_rows=list(state.get("train_examples") or []),
        eval_rows=list(getattr(eval_set, "all", []) or []),
        eval_source_ban=list(state.get("eval_source_ban") or []),
        requested_rows=want,
        query_variant=_entropy_seed() % 8,
        log=lambda message: _log(model_id, message),
    )
    return rows, report


def _mine_new_real(
    state: AgentState,
    plan: dict,
    *,
    model_id: str,
    eval_set,
) -> tuple[list[dict], dict]:
    """The `mine_new_real` ladder, in order, stopping as soon as it has enough rows.

        1. datasets this run already sourced that still have rows we have not taken;
        2. web research for a dataset we have never used, but only once (1) is empty.

    After MAX_FAILED_DISCOVERY_ROUNDS consecutive discovery rounds that contribute nothing, mining
    is retired for the rest of the run and the orchestrator is left with surgical synthesis. Both
    exhaustion events are logged loudly, because "mining added nothing" and "mining had nothing
    left to add" are different facts and the run used to report them identically.
    """
    from agent.data_rebuild import MAX_FAILED_DISCOVERY_ROUNDS, unexhausted_sources

    want = int(plan["rows"])
    report: dict = {"stage": None, "requested": want, "sources_exhausted": [],
                    "discovery_attempted": False}

    rows, newly_exhausted = _reread_known_sources(state, want=want, model_id=model_id)
    report["sources_exhausted"] = newly_exhausted
    report["candidates_seen"] = len(rows)
    if rows:
        report["stage"] = "known_sources"
        return rows, report

    remaining = unexhausted_sources(state)
    if not remaining:
        _log(
            model_id,
            "  ⚠ MINING: every dataset this run has sourced is EXHAUSTED — "
            f"{[s.hf_id for s in _task_spec(state).mining_sources]} have no rows left that the "
            "curriculum does not already contain. Falling through to web research for a dataset "
            "we have not used.",
        )
    failed = int(state.get("failed_discovery_rounds", 0) or 0)
    if failed >= MAX_FAILED_DISCOVERY_ROUNDS:
        _log(
            model_id,
            f"  ⚠ MINING RETIRED: web research has already failed {failed} time(s) to contribute "
            "a single novel row, and every known source is exhausted. mine_new_real can no longer "
            "add data; surgical_synthesis is the only remaining data intervention for this run.",
        )
        report["stage"] = "retired"
        return [], report

    report["discovery_attempted"] = True
    discovered, discovery_report = _discover_new_source(
        state, want=want, model_id=model_id, eval_set=eval_set,
    )
    report["stage"] = "discovery"
    report["discovery"] = discovery_report
    report["candidates_seen"] = int(discovery_report.get("candidate_rows", 0) or 0)
    if discovered:
        state["failed_discovery_rounds"] = 0
        # A discovered dataset is an ASSET, not a one-off delivery. Registering it in
        # `source_progress` — with `consumed` set to what this rebuild actually takes — means the next
        # mine_new_real rebuild re-reads it deeper from rung 1, for free, instead of paying Exa to
        # rediscover it or concluding there is nothing left to mine. Without this, discovery found a
        # corpus, drained whatever it happened to return in one pass, and forgot it existed.
        kept = discovered[:MAX_MINED_ROWS_PER_REBUILD]
        if len(discovered) > len(kept):
            _log(model_id,
                 f"  [mine] discovery returned {len(discovered)} row(s); taking "
                 f"{len(kept)} this rebuild (ceiling {MAX_MINED_ROWS_PER_REBUILD}) and recording the "
                 f"source so the remainder is available to the next one")
        _register_discovered_source(state, discovery_report, taken=len(kept), model_id=model_id)
        return kept, report

    state["failed_discovery_rounds"] = failed + 1
    _log(
        model_id,
        f"  ⚠ MINING: web research round {failed + 1} of {MAX_FAILED_DISCOVERY_ROUNDS} found no "
        "dataset contributing a novel row."
        + (
            " One more failure retires mine_new_real for this run."
            if failed + 1 < MAX_FAILED_DISCOVERY_ROUNDS
            else " mine_new_real is now RETIRED for this run."
        ),
    )
    return [], report


def curate_node(state: AgentState) -> AgentState:
    """Grow the curriculum by one data_rebuild, or build it for the first time.

    The curriculum is CUMULATIVE. Cold start loads gold rows; every rebuild ADDS to what is already
    there; rows leave only via quality control or the eval firewall. Nothing re-draws from a pool it
    has already drawn from — that was the removed gold FILL, which re-selected the same ~3,235 rows
    and honestly reported `0 novel` on eight consecutive rebuilds of one run.

    Exactly two things can add rows, and the plan names one of them:

        mine_new_real       real rows, from an unexhausted known dataset or a newly discovered one
        surgical_synthesis  teacher-generated rows aimed at the failure categories that are costing
                            the most points
    """
    from agent.data_rebuild import (
    DataInterventionUnavailable,
        MINE_NEW_REAL,
        SURGICAL_SYNTHESIS,
        fallback_data_rebuild_plan,
        mining_available_for_state,
        normalize_data_rebuild_plan,
    )

    task = state["task"]
    selected = state.get("selected_model")
    if selected is None:
        raise RuntimeError("curate_node called before a model was selected")
    model_id = selected.label
    intervention = state.get("last_intervention", "data_rebuild")
    if intervention != "data_rebuild":
        _log(model_id, f"SKIP: intervention={intervention} — dataset held fixed")
        return state
    eval_set = state.get("eval_set")
    if eval_set is None:
        raise RuntimeError("curate_node requires a fixed eval_set before rebuilding data")

    spec = _task_spec(state)
    firewall_tally: dict[str, int] = {}
    previous_rows = _read_jsonl(state.get("current_dataset_path"))
    previous_texts = _normalized_texts(previous_rows)
    hypothesis = state.get("last_hypothesis") or ""

    added: list[dict] = []
    n_added = 0
    plan: dict | None = None
    mining_report: dict = {}

    # The first curriculum, as opposed to a rebuild. Named because three later blocks need it and
    # `not previous_rows` re-derived at each of them is a correctness question at every site.
    initial = not previous_rows
    if initial:
        # FIRST BUILD. The curriculum is the gold rows the loader returned, decontaminated against
        # the held-out eval set. No plan, no strategy — there is nothing to add to yet.
        curriculum, dropped = _exclude_eval_rows(
            _tag_train_rows(
                list(state.get("train_examples") or []),
                default_source=str(state.get("data_source") or spec.title),
            ),
            eval_set,
            tally=firewall_tally,
            layer="initial_gold",
            log=lambda m: _log(model_id, m),
        )
        n_added = len(curriculum)
        _log(
            model_id,
            f"INITIAL CURRICULUM: {len(curriculum)} gold row(s) from {spec.title}"
            + (f" ({dropped} removed by the eval firewall)" if dropped else ""),
        )
    else:
        raw_plan = state.get("data_rebuild_plan")
        # Both gates, not just mining. `iterate` validated this plan a turn ago, but mining
        # availability is re-derived HERE against the decontaminated pool and can flip to False in
        # between — and when it does, the validator rewrites `mine_new_real` to `surgical_synthesis`.
        # Omitting `synthesis_allowed` let that rewrite land behind a teacher that had FAILED its
        # fitness gate, spending the teacher budget on exactly the output the gate exists to refuse.
        from agent.teacher_fitness import synthesis_allowed

        mining_available = mining_available_for_state(state)
        can_synth = synthesis_allowed(state)
        try:
            if isinstance(raw_plan, dict):
                plan = normalize_data_rebuild_plan(
                    raw_plan, task=task, hypothesis=hypothesis,
                    mining_available=mining_available,
                    synthesis_allowed=can_synth,
                )
            else:
                plan = fallback_data_rebuild_plan(state, hypothesis=hypothesis)
        except DataInterventionUnavailable as unavailable:
            # Neither route can add a row, and unlike `iterate` this node cannot switch the
            # intervention — training has already been scheduled against this decision. So the
            # curriculum passes through unchanged and the iteration is reported as adding nothing,
            # which is the truth. Raising here would kill a run over one bad turn; `run_health`
            # stops it on the SECOND consecutive empty rebuild, which is the pattern that matters.
            _log(model_id, f"  ✗ ERROR: data_rebuild cannot add rows ({unavailable}). The "
                           f"curriculum is unchanged, so this iteration re-trains on identical "
                           f"data — a wasted train+eval cycle.")
            plan = None
        state["data_rebuild_plan"] = plan

    if not initial and plan is None:
        # No usable plan: keep the curriculum, and let the health observer at the end of this node
        # count the empty rebuild.
        dataset = list(previous_rows)
        mining_report = {"stage": "unavailable"}
    elif not initial:
        categories = ", ".join(
            f"{entry['category']}({entry['count']})" for entry in plan["target_categories"]
        ) or "none reported"
        _log(
            model_id,
            f"DATA REBUILD: {plan['strategy']} — asking for {plan['rows']} new row(s). "
            f"Targeting: {categories}",
        )

        state["_last_synth_attempted"] = 0
        state["_last_synth_kept"] = 0
        if plan["strategy"] == MINE_NEW_REAL:
            added, mining_report = _mine_new_real(
                state, plan, model_id=model_id, eval_set=eval_set,
            )
            added, removed = _exclude_eval_rows(
                _tag_mined_rows(added), eval_set, tally=firewall_tally, layer="mined",
                log=lambda m: _log(model_id, m),
            )

            if removed:
                _log(model_id, f"  Eval firewall removed {removed} mined row(s)")
            # Mined rows join the persistent pool as well as the curriculum, so a later re-read
            # counts them as already consumed.
            if added:
                state["train_examples"] = _merge_persistent_train_rows(
                    list(state.get("train_examples") or []), added, eval_set,
                    tally=firewall_tally,
                )
        elif plan["strategy"] == SURGICAL_SYNTHESIS:
            added = _surgical_synthesize(
                state, plan, list(state.get("train_examples") or []),
                model_id=model_id, eval_set=eval_set,
            )
            added, removed = _exclude_eval_rows(
                added, eval_set, tally=firewall_tally, layer="synthesis",
                log=lambda m: _log(model_id, m),
            )
            if removed:
                _log(model_id, f"  Eval firewall removed {removed} generated row(s)")
        else:  # pragma: no cover - the normalizer rejects anything else
            raise ValueError(f"unknown data_rebuild strategy {plan['strategy']!r}")

        curriculum, n_added = _dedupe_into(previous_rows, added)

    # A rebuild that adds nothing trains on a curriculum identical to the previous iteration's, so
    # the iteration cannot tell us anything. That used to be reported as an ordinary `0 novel` line
    # among twenty others; it is an ERROR, because it means an intervention was chosen, a plan was
    # built, and the mechanism it named could not do the thing it exists to do.
    if plan is not None and n_added == 0:
        _log(
            model_id,
            f"  ✗ ERROR: data_rebuild/{plan['strategy']} added 0 new rows. The curriculum is "
            f"unchanged at {len(curriculum)} row(s), so training this iteration would repeat the "
            f"previous one exactly. See the [mine]/[synth] lines above for which stage produced "
            f"nothing.",
        )

    dataset = _annotate_generation_cot(curriculum, state, model_id=model_id)
    _pre_qc = len(dataset)
    dataset = apply_quality_controls(
        dataset,
        task=task,
        allowed_labels=spec.qc_context_labels(eval_set),
        log=lambda message: _log(model_id, message),
    )
    _post_qc = len(dataset)
    if _post_qc < _pre_qc:
        _log(model_id, f"  Quality control removed {_pre_qc - _post_qc} row(s) total "
                       f"({_pre_qc} → {_post_qc})")
    dataset, removed_final = _exclude_eval_rows(
        dataset, eval_set, tally=firewall_tally, layer="final",
        log=lambda m: _log(model_id, m),
    )
    if removed_final:
        _log(model_id, f"  Final eval firewall removed {removed_final} row(s)")
    firewall_total = sum(firewall_tally.values())
    _log(
        model_id,
        f"  Eval firewall: {firewall_total} row(s) removed across {len(firewall_tally)} "
        f"checkpoint(s) [{', '.join(f'{k}={v}' for k, v in firewall_tally.items())}]",
    )
    _enforce_curriculum_floor(dataset, model_id=model_id, target_rows=spec.initial_train_cap)

    next_version = int(state.get("dataset_version", 0) or 0) + 1
    for row in dataset:
        row["_dataset_version"] = next_version
    os.makedirs(ARTIFACTS_DIR, exist_ok=True)
    path = os.path.join(ARTIFACTS_DIR, f"dataset_v{next_version}.jsonl")
    atomic_write_jsonl(path, dataset)
    state["dataset_version"] = next_version
    state["current_dataset_path"] = path

    provenance = Counter(str(row.get("_provenance") or "unknown") for row in dataset)
    default_source = str(state.get("data_source") or spec.title)
    source_composition = Counter(_source_key(row, default_source) for row in dataset)
    gold_by_source = Counter(
        _source_key(row, default_source)
        for row in dataset
        if str(row.get("_provenance") or "") in GOLD_PROVENANCE_TAGS
    )
    final_texts = _normalized_texts(dataset)
    novel_rows = len(final_texts - previous_texts) if previous_rows else len(final_texts)
    novel_by_source = Counter(
        source_key(row, default_source)
        for row in dataset
        if normalize_text(_row_text(row)) not in previous_texts
    )
    source_usage = build_source_usage(
        dataset,
        source_records=list(state.get("data_sources") or []),
        novel_by_source=dict(novel_by_source),
        default=default_source,
    )
    state["last_curation"] = {
        "total_examples": len(dataset),
        "rows_added": n_added,
        "previous_rows": len(previous_rows),
        "novel_rows": novel_rows,
        "strategy": (plan or {}).get("strategy", "initial_gold"),
        "target_categories": (plan or {}).get("target_categories", []),
        "data_rebuild_plan": plan,
        "mining_report": mining_report,
        "source_progress": dict(state.get("source_progress") or {}),
        "failed_discovery_rounds": int(state.get("failed_discovery_rounds", 0) or 0),
        "n_gold": sum(provenance.get(tag, 0) for tag in GOLD_PROVENANCE_TAGS),
        "gold_by_source": dict(gold_by_source),
        "n_synth_total": sum(provenance.get(tag, 0) for tag in SYNTHETIC_PROVENANCE_TAGS),
        "n_hard_source": provenance.get("mined_real", 0),
        "provenance_composition": dict(provenance),
        "source_composition": dict(source_composition),
        "source_usage": source_usage,
        "label_dist": dict(Counter(_label_key(row, task) for row in dataset)),
        "eval_firewall": {"total": firewall_total, "by_layer": dict(firewall_tally)},
    }
    state["data_source_usage"] = list(state.get("data_source_usage") or []) + [{
        "iteration": int(state.get("iteration", 0) or 0),
        "dataset_version": f"v{next_version}",
        "strategy": (plan or {}).get("strategy", "initial_gold"),
        "sources": source_usage,
    }]

    # SEED SNAPSHOT for the reset ablation. A no-op unless
    # SLM_ABLATION_RESET_DATA_ON_ESCALATION=1, and only ever taken on the FIRST build. It sits
    # here, after `last_curation`, rather than beside the artifact write above, because the
    # snapshot keeps the seed's composition record too — and that is the thing a later reset
    # restores so the curriculum it republishes is described honestly instead of as zero rows.
    if initial:
        from agent.ablations import capture_seed_snapshot

        capture_seed_snapshot(state, path, log=lambda m: _log(model_id, m))

    _log_dataset_report(model_id, dataset, task=task, provenance=dict(provenance))
    _log(
        model_id,
        f"  CURRICULUM: {len(previous_rows)} → {len(dataset)} row(s) "
        f"(+{n_added} added this rebuild, {novel_rows} novel overall)",
    )
    _log(model_id, f"  Saved: {path}")

    # Cross-iteration health. A single fruitless rebuild is survivable; a pattern of them is a run
    # that cannot learn anything, and nothing used to be watching across iterations — which is how
    # run 38566712 spent 7h42m on eight consecutive empty rebuilds. Raises RunHealthError to stop
    # the run with the diagnosis attached.
    from agent.run_health import IterationRecord, observe_iteration

    observe_iteration(
        state,
        IterationRecord(
            # The iteration this curriculum will be TRAINED on, which is the next one — curate
            # runs before the counter advances. Recording the current value made every row of the
            # attribution table join to the previous iteration's score, so a synthesis round's rows
            # were reported against a hyperparameter step's result.
            iteration=int(state.get("iteration", 0) or 0) + 1,
            # `initial_gold` only when this really is the first curriculum. A rebuild whose plan
            # was unusable must be reported as a REBUILD that added nothing, or the health observer
            # reads it as an initial load and never counts the wasted cycle.
            strategy=(
                "initial_gold" if initial
                else str(plan["strategy"]) if plan else "unavailable"
            ),
            rows_added=n_added,
            curriculum_before=len(previous_rows),
            curriculum_after=len(dataset),
            qc_removed=max(0, _pre_qc - _post_qc),
            qc_examined=_pre_qc,
            firewall_removed=firewall_total,
            candidates_seen=int(mining_report.get("candidates_seen", 0) or 0),
            verify_attempted=int(state.get("_last_synth_attempted", 0) or 0),
            verify_kept=int(state.get("_last_synth_kept", 0) or 0),
        ),
        log=lambda message: _log(model_id, message),
    )

    # A REBUILD THAT ADDED NOTHING SKIPS TRAIN AND EVALUATE.
    #
    # Reached only after `observe_iteration` above, so every health counter has already been
    # incremented and any fatal pattern has already raised: mining still retires after 2 empty
    # rounds, synthesis still stops the run after 3, and the generic empty-rebuild budget of 4 is
    # untouched. The skip changes what happens on a SURVIVING empty rebuild, not whether one counts.
    #
    # `initial` is excluded because the first curriculum load adds every row it has and there is
    # nothing yet to train on twice. A plan that could not run at all (`plan is None`) is included:
    # it is the same wasted cycle by a different route.
    if not initial and n_added <= 0:
        state["iteration"] = int(state.get("iteration", 0) or 0) + 1
        _record_skipped_iteration(state, model_id=model_id, plan=plan, curriculum=len(dataset))
        _log(
            model_id,
            f"  ⏭  SKIPPING train+eval for iteration {state['iteration']}: the rebuild added 0 "
            f"rows, so the curriculum is byte-identical to the last one that was trained. "
            f"Returning to iterate for a different intervention.",
        )
        state["next_action"] = "iterate"
    return state


def _record_skipped_iteration(state: AgentState, *, model_id: str, plan, curriculum: int) -> None:
    """Put the skipped attempt in the DAG, marked, with NO score.

    It has to be visible: the orchestrator is shown the DAG as its own history, and an attempt that
    left no trace would be proposed again verbatim. But it must not carry a score, because there was
    no evaluation — inventing one (carrying the previous iteration's forward, say) would put a
    fabricated measurement into the trajectory the rollback and stagnation logic read.

    `status` is what every score-based consumer keys on to leave it alone. `_dag_rows` skips it in
    the attribution table, and `agent.nodes.iterate` skips it when measuring stagnation: a turn that
    produced no measurement is not evidence that the model has stopped improving.
    """
    dag = list(state.get("dag") or [])
    selected = state.get("selected_model")
    dag.append({
        "iteration": int(state.get("iteration", 0) or 0),
        "status": SKIPPED_NO_ROWS,
        "score": None,
        "pruned": False,
        "intervention": "data_rebuild",
        "model": getattr(selected, "selector", None) or model_id,
        "selector": getattr(selected, "selector", None),
        "tier": getattr(selected, "tier", None),
        "hypothesis": state.get("last_hypothesis", ""),
        "pi": {"D": {
            "version": state.get("dataset_version"),
            "path": state.get("current_dataset_path"),
            "plan": deepcopy(plan),
            "composition": {"total_examples": curriculum},
        }},
    })
    state["dag"] = dag
